
### Extrato
GET http://localhost:9999/clientes/1/extrato
Content-Type: application/json

### Transação
POST http://localhost:9998/clientes/1/transacoes
Content-Type: application/json

{
  "valor": "1000",
  "tipo" : "d",
  "descricao" : "devolve"
}
