version: "3.5"

services:
  api01: &api
    image: luizp/rinha-de-backend-bank:1.0.0-SNAPSHOT
    environment:
      - quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5432/dbrinha
      - quarkus.datasource.username=rinha
      - quarkus.datasource.password=backend
      - quarkus.datasource.reactive.max-size=10
      - quarkus.log.level=OFF
      - quarkus.http.port=8081
    network_mode: "host"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "100MB"

  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api
    environment:
      - quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5432/dbrinha
      - quarkus.datasource.username=rinha
      - quarkus.datasource.password=backend
      - quarkus.datasource.reactive.max-size=10
#      - quarkus.log.level=OFF
      - quarkus.http.port=8082

  nginx:
    image: nginx:latest
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "20MB"

  db:
    image: postgres:latest
    network_mode: "host"
    environment:
      - POSTGRES_PASSWORD=backend
      - POSTGRES_USER=rinha
      - POSTGRES_DB=dbrinha
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "200MB"
