-- public.conta_corrente definition

-- Drop table

-- DROP TABLE public.conta_corrente;

CREATE TABLE public.conta_corrente
(
    id     int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    nome   varchar(255) NULL,
    saldo  int8 NULL,
    limite int8 NULL,
    CONSTRAINT conta_corrente_pk PRIMARY KEY (id)
);

INSERT INTO public.conta_corrente (nome, saldo, limite)
VALUES ('odorico paraguaçu', 0, 80000),
       ('irmas cajazeira', 0, 10000000),
       ('coronel nepomuceno', 0, 500000),
       ('dirceu borboleta', 0, 1000000),
       ('zeca diabo', 0, 100000);

-- public.conta_corrente complete

-- public.movimentos definition

-- Drop table

-- DROP TABLE public.movimentos;

CREATE TABLE public.movimentos
(
    id             int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_cliente     int4 NULL,
    valor          int8 NULL,
    tipo           varchar(1) NULL,
    descricao      varchar(10) NULL,
    data_movimento timestamp NULL,
    CONSTRAINT movimentos_pk PRIMARY KEY (id)
);

-- DROP ROLE rinha;

-- DROP ROLE rinha;

CREATE ROLE rinha WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    LOGIN
    NOREPLICATION
    NOBYPASSRLS
    CONNECTION LIMIT -1;

-- Permissions

GRANT INSERT, SELECT, REFERENCES, DELETE, TRUNCATE, UPDATE, TRIGGER ON TABLE public.conta_corrente TO rinha;
GRANT INSERT, SELECT, REFERENCES, DELETE, TRUNCATE, UPDATE, TRIGGER ON TABLE public.movimentos TO rinha;

ALTER USER rinha WITH PASSWORD 'backend';