-- public.contacorrente definition

-- Drop table

-- DROP TABLE public.contacorrente;

CREATE TABLE public.contacorrente
(
    id     int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    nome   varchar(255) NULL,
    saldo  int8 NULL,
    limite int8 NULL,
    CONSTRAINT contacorrente_pk PRIMARY KEY (id)
);

INSERT INTO public.contacorrente (nome, saldo, limite)
VALUES ('odorico paraguaçu', 0, 80000),
       ('irmas cajazeira', 0, 10000000),
       ('coronel nepomuceno', 0, 500000),
       ('dirceu borboleta', 0, 1000000),
       ('zeca diabo', 0, 100000);

-- public.contacorrente complete

-- public.movimento definition

-- Drop table

-- DROP TABLE public.movimento;

CREATE TABLE public.movimento
(
    id             int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_cliente     int4 NULL,
    valor          int8 NULL,
    tipo           varchar(1) NULL,
    descricao      varchar(10) NULL,
    data_movimento timestamp NULL,
    CONSTRAINT movimento_pk PRIMARY KEY (id)
);

-- DROP ROLE rinha;

-- DROP ROLE rinha;

CREATE ROLE rinha WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    LOGIN
    NOREPLICATION
    NOBYPASSRLS
    CONNECTION LIMIT -1;

-- Permissions

GRANT INSERT, SELECT, REFERENCES, DELETE, TRUNCATE, UPDATE, TRIGGER ON TABLE public.contacorrente TO rinha;
GRANT INSERT, SELECT, REFERENCES, DELETE, TRUNCATE, UPDATE, TRIGGER ON TABLE public.movimento TO rinha;

ALTER USER rinha WITH PASSWORD 'backend';